
CREATE TABLE "CLIENTE" (
    "ID" INTEGER NOT NULL,
    "Nombre" TEXT NOT NULL,
    "Apellido" TEXT NOT NULL,
    "Email" TEXT,
    "FechaRegistro" TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("ID")
);

CREATE TABLE "TELEFONO" (
    "ID" INTEGER NOT NULL,
    "Numero" TEXT NOT NULL,
    "Tipo" TEXT DEFAULT 'Personal',
    "FKCLIENTE" INTEGER NOT NULL,
    PRIMARY KEY("ID"),
    CONSTRAINT "FK_TELEFONO_CLIENTE"
        FOREIGN KEY("FKCLIENTE")
        REFERENCES "CLIENTE"("ID")
);

